# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_jobui(object):
    def setupUi(self, jobui):
        jobui.setObjectName("jobui")
        jobui.resize(640, 508)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        jobui.setWindowIcon(icon)
        jobui.setToolTipDuration(-1)
        self.label = QtWidgets.QLabel(jobui)
        self.label.setGeometry(QtCore.QRect(60, 120, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(jobui)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(jobui)
        self.label_3.setGeometry(QtCore.QRect(250, 220, 351, 201))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(jobui)
        self.lineEdit.setGeometry(QtCore.QRect(60, 140, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(jobui)
        self.pushButton.setGeometry(QtCore.QRect(460, 140, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(jobui)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 440, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(jobui)
        self.label_4.setGeometry(QtCore.QRect(240, 90, 181, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_province1 = QtWidgets.QComboBox(jobui)
        self.comboBox_province1.setGeometry(QtCore.QRect(50, 220, 69, 22))
        self.comboBox_province1.setObjectName("comboBox_province1")
        self.comboBox_city1 = QtWidgets.QComboBox(jobui)
        self.comboBox_city1.setGeometry(QtCore.QRect(130, 220, 69, 22))
        self.comboBox_city1.setObjectName("comboBox_city1")
        self.label_5 = QtWidgets.QLabel(jobui)
        self.label_5.setGeometry(QtCore.QRect(90, 200, 91, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_city2 = QtWidgets.QComboBox(jobui)
        self.comboBox_city2.setGeometry(QtCore.QRect(130, 280, 69, 22))
        self.comboBox_city2.setObjectName("comboBox_city2")
        self.label_6 = QtWidgets.QLabel(jobui)
        self.label_6.setGeometry(QtCore.QRect(90, 260, 91, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox_province2 = QtWidgets.QComboBox(jobui)
        self.comboBox_province2.setGeometry(QtCore.QRect(50, 280, 69, 22))
        self.comboBox_province2.setObjectName("comboBox_province2")
        self.comboBox_city3 = QtWidgets.QComboBox(jobui)
        self.comboBox_city3.setGeometry(QtCore.QRect(130, 340, 69, 22))
        self.comboBox_city3.setObjectName("comboBox_city3")
        self.label_7 = QtWidgets.QLabel(jobui)
        self.label_7.setGeometry(QtCore.QRect(90, 320, 91, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_province3 = QtWidgets.QComboBox(jobui)
        self.comboBox_province3.setGeometry(QtCore.QRect(50, 340, 69, 22))
        self.comboBox_province3.setObjectName("comboBox_province3")
        self.comboBox_city4 = QtWidgets.QComboBox(jobui)
        self.comboBox_city4.setGeometry(QtCore.QRect(130, 400, 69, 22))
        self.comboBox_city4.setObjectName("comboBox_city4")
        self.label_8 = QtWidgets.QLabel(jobui)
        self.label_8.setGeometry(QtCore.QRect(90, 380, 91, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_province4 = QtWidgets.QComboBox(jobui)
        self.comboBox_province4.setGeometry(QtCore.QRect(50, 400, 69, 22))
        self.comboBox_province4.setObjectName("comboBox_province4")

        self.retranslateUi(jobui)
        QtCore.QMetaObject.connectSlotsByName(jobui)

    def retranslateUi(self, jobui):
        _translate = QtCore.QCoreApplication.translate
        jobui.setWindowTitle(_translate("jobui", "招聘系统数据分析平台"))
        self.label.setText(_translate("jobui", "请输入关键词："))
        self.label_2.setText(_translate("jobui", "招聘系统数据分析平台"))
        self.pushButton.setText(_translate("jobui", "立 即 分 析"))
        self.pushButton_2.setText(_translate("jobui", "点击查看报告"))
        self.label_4.setText(_translate("jobui", "By  蒋傲天        version 1.0"))
        self.label_5.setText(_translate("jobui", "请选择地市1："))
        self.label_6.setText(_translate("jobui", "请选择地市2："))
        self.label_7.setText(_translate("jobui", "请选择地市3："))
        self.label_8.setText(_translate("jobui", "请选择地市4："))

